name: build-lib-mac
on:
  push:
    branches:
      - master
jobs:
  build-and-publish:
    runs-on: macos-latest
    env:
      working-directory: ./VFX/src
    steps:
      - uses: actions/checkout@v2
      - name: build-x64
        run: gcc-11 -shared -o VFXLib_MAC64.so -fPIC VFXWrapper.c LensFlare.c HighPass.c ChromaticAberration.c Utils.c
        working-directory: ${{env.working-directory}}
      - uses: actions/upload-artifact@v2
        with:
          path: ./VFX/src/VFXLib_MAC64.so